server:
  port: 8090

# ??????
#chatgpt-bot:
#  launchList: group01,group02 # ??????????
#  group01:
#    groupName: ChatGPT AI ????
#    groupId: 28885518425541 # ????ID
#    cookie:  # ??????cookie??
#    openAiKey:  # ???? https://beta.openai.com/overview ??????? fustack ??????????????????
#    cronExpression: 0/30 * * * * ? # ???????????cron.qqe2.com
#    silenced: false
#  group02:
#    groupName: ????
#    groupId: 28885518425541 # ????ID
#    cookie:  # ??????cookie??
#    openAiKey:  # ???? https://beta.openai.com/overview ??????? fustack ??????????????????
#    cronExpression: 0/30 * * * * ? # ???????????cron.qqe2.com
#    silenced: true